{
 "title": "Flask Application Monitoring",
 "tags": [
  "flask",
  "prometheus",
  "devops"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(flask_http_request_total)", "legendFormat": "requests" }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 3 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{status=\"500\"})"
    }
   ]
  },
  {
   "title": "4xx Errors",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 3 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{status=\"404\"})"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "graph",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_total[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Duration (Latency)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(flask_http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Requests per Endpoint",
   "type": "graph",
   "gridPos": { "x": 0, "y": 10, "w": 24, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}